name: build
on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential libtool meson ninja-build pkg-config \
            libcapstone-dev device-tree-compiler libglib2.0-dev gnutls-bin \
            libjpeg-turbo8-dev libpng-dev libslirp-dev libssh-dev \
            libusb-1.0-0-dev liblzo2-dev libncurses5-dev libpixman-1-dev \
            libsnappy-dev vde2 zstd libgnutls28-dev libgmp10 libgmp3-dev \
            lzfse liblzfse-dev

      - name: Build nettle 3.10.2
        run: |
          wget https://ftpmirror.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz
          echo "fe9ff51cb1f2abb5e65a6b8c10a92da0ab5ab6eaf26e7fc2b675c45f1fb519b5  nettle-3.10.2.tar.gz" | sha256sum -c -
          tar -xf nettle-3.10.2.tar.gz
          cd nettle-3.10.2
          ./configure
          make -j$(nproc)
          sudo make install

      - name: Build QEMU
        run: |
          mkdir build && cd build
          PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig ../configure \
            --target-list=aarch64-softmmu,x86_64-softmmu \
            --disable-linux-user \
            --disable-guest-agent \
            --enable-capstone \
            --enable-slirp \
            --enable-lzfse \
            --enable-nettle \
            --enable-gnutls \
            --disable-werror \
            --disable-tests \
            --disable-qom-cast-debug \
            --disable-plugins
          make -j$(nproc)

      - name: Package artifacts
        run: |
          mkdir dist
          cp build/qemu-system-* dist/
          cd dist
          tar -czf qemu-linux-x86_64-aarch64.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-linux-build
          path: dist/qemu-linux-x86_64-aarch64.tar.gz
